import { ArrowRight, CalendarDays, Check, Clock3, Heart, Lightbulb, Sparkles, Target } from 'lucide-react'
import { useEffect, useState } from 'react'
import { deadlineInfo } from '../lib/reminders'

export function DashboardPage({ items, setPage, setSelected, onReflect, onInsights, reminders, reminderNotice, userName = 'Ananya', attendedIds = [], acceptedIds = [], feedbackIds = [] }) {
  const [loading, setLoading] = useState(true)
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 300); return () => window.clearTimeout(timer) }, [])
  const attended = items.filter((item) => item.completed || attendedIds.includes(item.id))
  const saved = items.filter((item) => reminders.includes(item.id) && !deadlineInfo(item.deadline).isPast)
  const growth = items.filter((item) => ['growth', 'stretch'].includes(item.category) && !attendedIds.includes(item.id)).slice(0, 3)
  const dreams = items.filter((item) => item.category === 'dream').slice(0, 3)
  if (loading) return <div className="page-wrap dashboard-loading"><div className="loading-orbit"><Target size={23} /></div><h1>Mapping your journey<span>...</span></h1><p>Turning your experiences into a clear next path.</p></div>
  return <div className="page-wrap journey-page">
    <section className="journey-header"><div><div className="eyebrow"><span className="eyebrow-dot" />YOUR JOURNEY</div><h1>Your Opportunity Journey</h1><p className="lead">Hey, {userName}. See where you are going and what will move you forward.</p></div><button className="button secondary" onClick={() => setPage('Home')}><ArrowRight size={15} /> Find my next opportunity</button></section>
    <section className="journey-summary"><div><span>Current level</span><strong>Building</strong></div><div><span>Opportunities accepted</span><strong>{acceptedIds.length}</strong></div><div><span>Current growth</span><strong>+18%</strong></div></section>
    <GrowthSection />
    <JourneyList title="MY DREAM OPPORTUNITIES" heading="Where you want to go" icon={Heart} action="Open Dream Board" onAction={() => setPage('Dreams')} empty="Choose a grand opportunity from your Dream Board.">{dreams.map((item) => <button className="journey-row" key={item.id} onClick={() => setSelected(item)}><div><strong>{item.title}</strong><span>{item.org} · {item.matchScore ?? item.score}% current match</span></div><b>{item.gapCount || item.missing?.length || 2} capabilities away</b><ArrowRight size={15} /></button>)}</JourneyList>
    <JourneyList title="GROWTH OPPORTUNITIES" heading="Build toward your dreams" icon={Sparkles} empty="Your next growth opportunity will appear here.">{growth.map((item) => <button className="journey-row" key={item.id} onClick={() => setSelected(item)}><div><strong>{item.title}</strong><span>Closes {item.deadline} · {item.growthValue}</span></div><span className="journey-tag">{item.missingSkills?.[0] || item.missing?.[0] || 'New capability'}</span><ArrowRight size={15} /></button>)}</JourneyList>
    <JourneyList title="YOUR EXPERIENCES" heading="What you have done" icon={Check} empty="Attend an opportunity to unlock feedback and insights.">{attended.map((item) => <div className="journey-row attended-row" key={item.id}><div><strong>{item.title}</strong><span>{item.date} · {item.org}</span></div><span className="attended-label">Attended</span>{feedbackIds.includes(item.id) ? <><button className="button secondary" onClick={() => onReflect(item)}><Lightbulb size={14} /> Give feedback</button><button className="text-button" onClick={() => onInsights(item)}>View insights</button></> : <button className="button secondary" onClick={() => onReflect(item)}><Lightbulb size={14} /> Give feedback</button>}</div>)}</JourneyList>
    <JourneyList title="SAVED REMINDERS" heading="Deadlines you chose" icon={Clock3} empty="Remind yourself from Home when a deadline matters.">{saved.map((item) => <div className="journey-row" key={item.id}><div><strong>{item.title}</strong><span>Deadline · {item.deadline}</span></div><CalendarDays size={15} /></div>)}</JourneyList>
    {reminderNotice && <div className="reminder-notice"><Clock3 size={15} />{reminderNotice}</div>}
  </div>
}

function GrowthSection() { return <section className="growth-chart journey-section"><div><div className="eyebrow"><Sparkles size={13} /> YOUR GROWTH</div><h2>Evidence is adding up.</h2><p>Skills gained, projects completed, attendance, feedback, and harder opportunities shape this view.</p></div><div className="journey-chart"><span>Month 1 <b>42</b></span><i><em style={{ width: '42%' }} /></i><span>Month 2 <b>51</b></span><i><em style={{ width: '51%' }} /></i><span>Month 3 <b>63</b></span><i><em style={{ width: '63%' }} /></i><span>Month 4 <b>71</b></span><i><em style={{ width: '71%' }} /></i></div></section> }
function JourneyList({ title, heading, icon: Icon, action, onAction, empty, children }) { return <section className="journey-section"><div className="journey-section-heading"><div><div className="eyebrow"><Icon size={13} /> {title}</div><h2>{heading}</h2></div>{action && <button className="text-button" onClick={onAction}>{action} <ArrowRight size={14} /></button>}</div>{children && <div className="journey-list">{children}</div>}{!children && <div className="journey-empty">{empty}</div>}</section> }
