import { BarChart3, CalendarClock, ChevronRight, CircleUserRound, FilePlus2, LogOut, UsersRound, X } from 'lucide-react'
import { useState } from 'react'
import { OrganizerPage } from './OrganizerPage'

const demoEvents = [
  { id: 'demo-ai', title: 'AI for Social Good Hackathon', status: 'Published', deadline: 'Oct 10, 2026', interested: 172, distribution: '24 strong · 61 good · 87 stretch' },
  { id: 'demo-web', title: 'Campus React Weekend Build', status: 'Published', deadline: 'Sep 21, 2026', interested: 94, distribution: '31 strong · 38 good · 25 stretch' },
]

export function OrganizerDashboard({ account, events, setEvents, onLogout }) {
  const [view, setView] = useState('dashboard')
  const allEvents = [...demoEvents, ...events]
  if (view === 'create') return <OrganizerPage onBack={() => setView('dashboard')} onPublished={(event) => { setEvents((current) => [...current, { ...event, id: `event-${Date.now()}`, status: 'Published', interested: 0, distribution: '0 strong · 0 good · 0 stretch' }]); setView('dashboard') }} />
  return <div className="organizer-dashboard"><header className="organizer-top"><div className="brand"><span className="brand-mark"><span /></span><span>grow<span>via</span></span></div><div className="organizer-user"><span className="organizer-avatar">GC</span><span><strong>{account.name}</strong><small>Organizer workspace</small></span><button className="icon-button" onClick={onLogout} title="Log out"><LogOut size={17} /></button></div></header><div className="organizer-shell"><aside className="organizer-nav"><div className="organizer-nav-label">WORKSPACE</div>{[['dashboard', BarChart3, 'Dashboard'], ['create', FilePlus2, 'Create Opportunity'], ['opportunities', CalendarClock, 'My Opportunities'], ['applicants', UsersRound, 'Applicants / Interested'], ['analytics', BarChart3, 'Analytics'], ['profile', CircleUserRound, 'Profile']].map(([key, Icon, label]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)}><Icon size={17} />{label}</button>)}<div className="organizer-nav-note"><strong>Reach the right students.</strong><span>Every event becomes an explainable Opportunity DNA.</span></div></aside><main className="organizer-main"><div className="organizer-main-heading"><div><div className="eyebrow">ORGANIZER OVERVIEW</div><h1>Build something<br /><em>worth chasing.</em></h1><p className="lead">Create opportunities, understand your reach, and let the matching engine find the right next people.</p></div><button className="button dark-button" onClick={() => setView('create')}><FilePlus2 size={16} /> Create Opportunity</button></div>{view === 'dashboard' && <DashboardOverview events={allEvents} setView={setView} />}{view === 'opportunities' && <EventsPanel events={allEvents} setView={setView} />}{view === 'applicants' && <AggregatePanel events={allEvents} />}{view === 'analytics' && <AggregatePanel events={allEvents} analytics />}{view === 'profile' && <div className="organizer-panel organizer-profile-panel"><div className="eyebrow">ORGANIZER PROFILE</div><h2>{account.name}</h2><p className="lead">Demo organization · {account.organizationType || 'Community'}</p><div className="organizer-profile-facts"><span>Contact person<br /><strong>{account.contact || 'Community team'}</strong></span><span>Email<br /><strong>{account.email}</strong></span></div></div>}</main></div></div>
}

function DashboardOverview({ events, setView }) { return <><div className="organizer-stat-grid"><Stat label="Total events" value={events.length} detail="2 published demo events" /><Stat label="Active events" value={events.filter((event) => event.status === 'Published').length} detail="All systems visible" /><Stat label="Upcoming deadlines" value="04" detail="Across your opportunities" /><Stat label="Student reach" value="266" detail="Aggregate interested students" /></div><div className="organizer-content-grid"><section className="organizer-panel organizer-events-panel"><div className="organizer-panel-heading"><div><div className="eyebrow">YOUR OPPORTUNITIES</div><h2>Events students can find</h2></div><button className="text-button" onClick={() => setView('opportunities')}>View all <ChevronRight size={14} /></button></div>{events.slice(0, 2).map((event) => <EventRow event={event} key={event.id} />)}</section><section className="organizer-panel reach-panel"><div className="eyebrow"><UsersRound size={13} /> MATCHING REACH</div><h2>266 students<br /><em>could grow here.</em></h2><p>Aggregate demo analytics show how your events meet students where they are.</p><div className="reach-bars"><span><i style={{ width: '28%' }} />Strong match <b>24</b></span><span><i style={{ width: '58%' }} />Good match <b>61</b></span><span><i style={{ width: '82%' }} />Stretch match <b>87</b></span></div></section></div></> }
function EventsPanel({ events, setView }) { return <section className="organizer-panel events-page-panel"><div className="organizer-panel-heading"><div><div className="eyebrow">MY OPPORTUNITIES</div><h2>Every event, one clear view.</h2></div><button className="button dark-button" onClick={() => setView('create')}><FilePlus2 size={15} /> Create Opportunity</button></div><div className="event-table">{events.map((event) => <EventRow event={event} key={event.id} detailed />)}</div></section> }
function AggregatePanel({ events, analytics }) { return <section className="organizer-panel events-page-panel"><div className="eyebrow"><UsersRound size={13} /> {analytics ? 'ANALYTICS' : 'APPLICANTS / INTERESTED STUDENTS'}</div><h2>{analytics ? 'Your opportunity reach is compounding.' : 'Aggregate matching, with privacy intact.'}</h2><p className="panel-copy">Student identities stay private in this prototype. You see how many students are likely to benefit, not personal profiles.</p><div className="aggregate-list">{events.map((event) => <div key={event.id}><strong>{event.title}</strong><span>{event.interested} interested students</span><small>{event.distribution}</small></div>)}</div></section> }
function EventRow({ event, detailed }) { return <div className={`event-row ${detailed ? 'detailed' : ''}`}><div><span className="event-status">{event.status}</span><strong>{event.title}</strong><small>Registration deadline · {event.deadline}</small></div><div className="event-match"><b>{event.interested}</b><span>interested</span><small>{event.distribution}</small></div>{detailed && <div className="event-actions"><button className="text-button">Edit</button><button className="text-button">View</button><button className="text-button">Close</button></div>}</div> }
function Stat({ label, value, detail }) { return <div className="organizer-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
