import { AlertCircle, ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, LoaderCircle, Pencil, Plus, Send, Upload, X } from 'lucide-react'
import { useRef, useState } from 'react'
import { createOpportunityDNA, extractPosterDetails } from '../lib/organizer'
import { publishOpportunity } from '../lib/supabase'

const fields = [['title', 'Event title'], ['description', 'Description'], ['domain', 'Domain'], ['date', 'Event date'], ['deadline', 'Registration deadline'], ['location', 'Location'], ['eligibility', 'Eligibility'], ['teamSize', 'Team size'], ['prize', 'Prize'], ['registrationUrl', 'Registration URL']]
const emptyEvent = { title: '', description: '', domain: '', date: '', deadline: '', location: '', eligibility: '', teamSize: '', prize: '', requiredSkills: [], registrationUrl: '' }

export function OrganizerPage({ onBack, onPublished }) {
  const [stage, setStage] = useState('upload')
  const [event, setEvent] = useState(emptyEvent)
  const [sourceFile, setSourceFile] = useState(null)
  const [error, setError] = useState('')
  const [publishing, setPublishing] = useState(false)
  const [published, setPublished] = useState(false)
  const fileInput = useRef(null)

  const processFile = async (file) => {
    if (!file) return
    setSourceFile(file.name)
    setError('')
    setStage('extracting')
    try { setEvent(await extractPosterDetails(file)); setStage('review') } catch { setEvent(emptyEvent); setStage('manual'); setError('We could not read this poster. You can enter the event details manually below.') }
  }
  const update = (key, value) => setEvent((current) => ({ ...current, [key]: value }))
  const publish = async () => {
    if (!event.title || !event.description || !event.domain || !event.date || !event.deadline || !event.location || !event.registrationUrl) { setError('Complete the required fields before publishing.'); setStage('review'); return }
    setPublishing(true); setError(''); const result = await publishOpportunity(event); setPublishing(false)
    if (result.error) { setError('Publishing failed. Please check your Supabase connection and try again.'); return }
    const publishedEvent = { ...event, opportunityDNA: createOpportunityDNA(event) }
    setPublished(true); setStage('published'); onPublished?.(publishedEvent)
  }

  return <div className="page-wrap organizer-page"><section className="welcome-row"><div><div className="eyebrow">ORGANIZER STUDIO</div><h1>Publish something<br />worth finding.</h1><p className="lead">Upload once. Review what AI found. Publish only when everything looks right.</p></div><button className="button secondary" onClick={onBack}><ArrowLeft size={15} />Back to student view</button></section><div className="organizer-steps">{[['upload', 'Upload poster'], ['extracting', 'AI extraction'], ['review', 'Review details'], ['published', 'Publish']].map(([key, label], index) => <div className={stage === key || (stage === 'manual' && key === 'review') ? 'organizer-step active' : ['review', 'published'].includes(stage) && index < 2 ? 'organizer-step done' : 'organizer-step'} key={key}><span>{['review', 'published'].includes(stage) && index === 0 ? <Check size={13} /> : index + 1}</span>{label}</div>)}</div><div className="organizer-grid"><section className="organizer-panel"><div className="panel-heading"><div><h2>{stage === 'upload' ? 'Start with an event poster' : stage === 'extracting' ? 'Reading your poster' : stage === 'published' ? 'Opportunity published' : stage === 'manual' ? 'Enter event details manually' : 'Review extracted information'}</h2><p>{stage === 'upload' ? 'AI will find the details students need to decide.' : stage === 'extracting' ? 'Finding dates, eligibility, skills, and registration details.' : 'Everything remains editable before it reaches the student radar.'}</p></div><span className="status-badge">{stage === 'published' ? 'Live' : stage === 'manual' ? 'Fallback form' : `Step ${stage === 'upload' ? 1 : stage === 'extracting' ? 2 : 3} of 4`}</span></div>{stage === 'upload' && <UploadStage fileInput={fileInput} processFile={processFile} onManual={() => { setError(''); setEvent(emptyEvent); setStage('manual') }} />} {stage === 'extracting' && <ExtractingStage sourceFile={sourceFile} />} {(stage === 'review' || stage === 'manual') && <ReviewStage event={event} update={update} sourceFile={sourceFile} onPublish={() => setStage('confirm')} onManual={() => setStage('manual')} error={error} />} {stage === 'confirm' && <ConfirmStage event={event} onBack={() => setStage('review')} onPublish={publish} publishing={publishing} />} {stage === 'published' && <PublishedStage event={event} onBack={onBack} />}</section><Checklist stage={stage} published={published} /></div></div>
}

function UploadStage({ fileInput, processFile, onManual }) { return <><input ref={fileInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,application/pdf" onChange={(event) => processFile(event.target.files?.[0])} /><button className="upload-zone organizer-upload" onClick={() => fileInput.current?.click()}><Upload size={27} /><strong>Upload event poster</strong><span>PNG, JPG or PDF · up to 10 MB</span></button><div className="demo-poster-row"><span>Try a demo format:</span><button onClick={() => processFile({ name: 'ai-summit-poster.png', type: 'image/png' })}>AI summit</button><button onClick={() => processFile({ name: 'cyber-ctf.jpg', type: 'image/jpeg' })}>Cyber CTF</button><button onClick={() => processFile({ name: 'pitch-night.pdf', type: 'application/pdf' })}>Pitch PDF</button></div><button className="manual-entry-button" onClick={onManual}>Or enter event details manually <ArrowRight size={13} /></button></> }
function ExtractingStage({ sourceFile }) { return <div className="extracting-state"><div className="loading-orbit"><LoaderCircle size={23} /></div><h3>Scanning {sourceFile}</h3><p>Looking for event dates, eligibility, prizes, and the details students care about.</p><div className="loading-lines"><i /><i /><i /></div></div> }
function ReviewStage({ event, update, sourceFile, onPublish, onManual, error }) { return <div className="review-form"><div className="source-file"><FileText size={18} /><span>{sourceFile || 'Manual event entry'}</span><button onClick={onManual}><Pencil size={13} />Edit manually</button></div>{fields.map(([key, label]) => <label className={key === 'description' ? 'wide-field' : ''} key={key}>{label}{key === 'description' ? <textarea value={event[key]} onChange={(input) => update(key, input.target.value)} rows="3" /> : <input value={event[key]} onChange={(input) => update(key, input.target.value)} />}</label>)}<label>Required skills<input value={event.requiredSkills.join(', ')} onChange={(input) => update('requiredSkills', input.target.value.split(',').map((skill) => skill.trim()).filter(Boolean))} placeholder="Python, teamwork, storytelling" /></label>{error && <div className="organizer-error"><AlertCircle size={16} />{error}</div>}<button className="button dark-button publish" onClick={onPublish}>Continue to publish <ArrowRight size={15} /></button></div> }
function ConfirmStage({ event, onBack, onPublish, publishing }) { return <div className="confirm-stage"><div className="confirm-icon"><Send size={22} /></div><h3>Ready to publish?</h3><p><strong>{event.title}</strong> will be visible to students after you confirm. You can edit it later from your organizer dashboard.</p><div className="confirm-summary"><span>{event.domain}</span><span>{event.date}</span><span>{event.location}</span></div><div className="confirm-actions"><button className="button secondary" onClick={onBack}><Pencil size={14} />Keep editing</button><button className="button dark-button" disabled={publishing} onClick={onPublish}>{publishing ? 'Publishing...' : 'Confirm & publish'} <Send size={14} /></button></div></div> }
function PublishedStage({ event, onBack }) { return <div className="published-state"><div className="published-icon"><CheckCircle2 size={31} /></div><h3>{event.title} is live.</h3><p>Your opportunity is now ready to be matched with students who can grow through it.</p><button className="button dark-button" onClick={onBack}>View student radar <ArrowRight size={15} /></button></div> }
function Checklist({ stage, published }) { const steps = ['Upload the event poster', 'Review extracted information', 'Confirm and publish']; return <aside className="organizer-aside"><div className="eyebrow">PUBLISHING CHECKLIST</div>{steps.map((item, index) => { const done = published || (index === 0 && stage !== 'upload') || (index === 1 && ['review', 'manual', 'confirm', 'published'].includes(stage)); return <div className={done ? 'check-row done' : 'check-row'} key={item}><span>{done ? <Check size={13} /> : index + 1}</span>{item}</div> })}<div className="organizer-note"><Plus size={15} /><strong>Reliable by design</strong><p>If a poster is hard to read, the manual fallback keeps your publishing flow moving.</p></div></aside> }
