import { ArrowUpRight, CalendarDays, Check, LoaderCircle, MapPin, Rocket, Target, Users, X } from 'lucide-react'
import { categoryMeta } from '../data/opportunities'
import { useEffect, useState } from 'react'

export function OpportunityDetails({ opportunity, onClose, reminder, onToggleReminder, saved, onToggleSaved, onPrepare }) {
  const [matchLoading, setMatchLoading] = useState(true)
  const [matchError, setMatchError] = useState('')
  useEffect(() => { try { const timer = window.setTimeout(() => setMatchLoading(false), 280); return () => window.clearTimeout(timer) } catch { setMatchError('We could not load the match explanation.') } }, [opportunity.id])
  const meta = categoryMeta[opportunity.category]
  const Icon = meta.icon
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><div className={`detail-hero ${opportunity.color}`}><span className={`category-pill ${meta.className}`}><Icon size={14} />{meta.label}</span><div className="org-name">{opportunity.org} · {opportunity.domain || opportunity.type}</div><h2>{opportunity.title}</h2><div className="detail-facts"><span><CalendarDays size={15} />{opportunity.date}</span><span><MapPin size={15} />{opportunity.location}</span><span><Users size={15} />Teams of 2–4</span></div></div><div className="detail-body">{matchLoading ? <div className="match-loading"><LoaderCircle size={18} />Generating your personalized explanation...</div> : matchError ? <div className="match-error"><Target size={18} />{matchError}</div> : <><div className="why-box"><Target size={18} /><div><strong>Why am I seeing this?</strong><p>{opportunity.why || opportunity.reason}</p></div></div><div className="match-summary"><span><b>{opportunity.matchScore ?? opportunity.score}%</b> match score</span><span><b>{opportunity.growthValue}</b> growth value</span></div><div className="detail-columns"><div><h4>Matching skills</h4><div className="skill-list">{(opportunity.matchingSkills || opportunity.skills).map((skill) => <span className="skill good" key={skill}><Check size={13} />{skill}</span>)}</div></div><div><h4>Missing skills</h4><div className="skill-list">{(opportunity.missingSkills || opportunity.missing).map((skill) => <span className="skill" key={skill}><Target size={13} />{skill}</span>)}</div></div></div></>}<div className="detail-actions"><button className="button dark-button" onClick={opportunity.category === 'stretch' ? onPrepare : onToggleReminder}>{opportunity.category === 'stretch' ? <><Rocket size={15} /> Prepare Me</> : reminder ? 'Reminder set' : 'Remind me'} <ArrowUpRight size={15} /></button><button className={saved ? 'button secondary saved' : 'button secondary'} onClick={onToggleSaved}><Check size={15} />{saved ? 'Saved' : 'Save opportunity'}</button></div></div></div></div>
}