import { AlertTriangle, ArrowUpRight, CalendarDays, Check, LoaderCircle, MapPin, Rocket, Target, Users, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { categoryMeta } from '../data/opportunities'

export function OpportunityDetails({ opportunity, onClose, reminder, onToggleReminder, saved, onToggleSaved, onPrepare, onAttend }) {
  const [matchLoading, setMatchLoading] = useState(true)
  useEffect(() => { const timer = window.setTimeout(() => setMatchLoading(false), 280); return () => window.clearTimeout(timer) }, [opportunity.id])
  const meta = categoryMeta[opportunity.category]
  const Icon = meta.icon
  const isCoachTarget = opportunity.category === 'stretch' || opportunity.readiness === 'DREAM'
  const matchingSkills = opportunity.matchingSkills || opportunity.skills || []
  const missingSkills = opportunity.missingSkills || opportunity.missing || []
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><div className={`detail-hero ${opportunity.color}`}><span className={`category-pill ${meta.className}`}><Icon size={14} />{meta.label}</span><div className="org-name">{opportunity.org} · {opportunity.domain || opportunity.type}</div><h2>{opportunity.title}</h2><div className="detail-facts"><span><CalendarDays size={15} />{opportunity.date}</span><span><MapPin size={15} />{opportunity.location}</span><span><Users size={15} />Teams of 2-4</span></div></div><div className="detail-body">{matchLoading ? <div className="match-loading"><LoaderCircle size={18} />Generating your personalized explanation...</div> : <><div className="why-box"><Target size={18} /><div><strong>Why am I seeing this?</strong><p>{opportunity.why || opportunity.reason}</p></div></div><div className="match-summary"><span><b>{opportunity.matchScore ?? opportunity.score}%</b> match score</span><span><b>{opportunity.readiness || 'NEXT'}</b> readiness · {opportunity.gapCount || 0} gaps</span></div><div className="detail-columns"><div><h4>Matching skills</h4><div className="skill-list">{matchingSkills.map((skill) => <span className="skill good" key={skill}><Check size={13} />{skill}</span>)}</div></div><div><h4>Missing skills</h4><div className="skill-list">{missingSkills.map((skill) => <span className="skill" key={skill}><Target size={13} />{skill}</span>)}</div></div></div><EvidencePanel opportunity={opportunity} /></>}<div className="detail-actions"><button className="button secondary" onClick={onAttend}><Check size={15} /> Mark attended</button><button className="button dark-button" onClick={isCoachTarget ? onPrepare : onToggleReminder}>{isCoachTarget ? <><Rocket size={15} /> Opportunity Coach</> : reminder ? 'Reminder Set' : 'Remind Me'} <ArrowUpRight size={15} /></button><button className={saved ? 'button secondary saved' : 'button secondary'} onClick={onToggleSaved}><Check size={15} />{saved ? 'Saved' : 'Save opportunity'}</button></div></div></div></div>
}

function EvidencePanel({ opportunity }) { const evidence = opportunity.matchingEvidence || []; const missing = (opportunity.missingSkills || []).slice(0, 2); return <div className="evidence-panel"><strong>Why did we recommend this?</strong><div>{evidence.slice(0, 4).map((item) => <span key={item.skill}><Check size={13} />{item.skill} - {item.sources[0]}</span>)}{missing.map((skill) => <span className="limited" key={skill}><AlertTriangle size={13} />{skill} - limited evidence</span>)}</div></div> }
