import { ArrowRight, Check, Clock3, Flame, Target, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { generatePreparation } from '../lib/preparation'

export function PrepareModal({ opportunity, studentDNA, onClose }) {
  const [state, setState] = useState({ loading: true, error: '', roadmap: null })
  const loadRoadmap = () => { setState({ loading: true, error: '', roadmap: null }); generatePreparation(studentDNA, opportunity).then((roadmap) => setState({ loading: false, error: '', roadmap })).catch(() => setState({ loading: false, error: 'We could not generate a roadmap right now. Try again in a moment.', roadmap: null })) }
  useEffect(() => { loadRoadmap() }, [opportunity.id])
  const roadmap = state.roadmap
  return <div className="modal-backdrop prepare-backdrop" onMouseDown={onClose}><div className="prepare-modal" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><div className={`prepare-hero ${opportunity.color}`}><div className="prepare-badge"><Flame size={15} /> STRETCH MODE</div><div className="eyebrow">YOUR PREPARATION PLAN</div><h2>Turn the gap into<br /><em>your advantage.</em></h2><p>{opportunity.title}</p></div><div className="prepare-body">{state.loading ? <div className="prepare-loading"><div className="prepare-spinner"><Target size={22} /></div><h3>Building your path in...</h3><p>Balancing what you know, what is missing, and the time you have left.</p></div> : state.error ? <div className="prepare-error"><Target size={20} /><h3>Roadmap unavailable</h3><p>{state.error}</p><button className="button secondary" onClick={loadRoadmap}>Try again <ArrowRight size={14} /></button></div> : <><div className="prepare-context"><div><span>Current match</span><strong>{opportunity.matchScore ?? opportunity.score}%</strong></div><div><span>Time to prepare</span><strong>{roadmap.daysAvailable} days</strong></div><div><span>Growth value</span><strong>{opportunity.growthValue}</strong></div></div><div className="prepare-focus"><div className="eyebrow"><Target size={13} /> FOCUS AREAS</div><div className="focus-chips">{roadmap.focus.map((skill) => <span key={skill}><Check size={12} />{skill}</span>)}</div></div><div className="roadmap"><div className="roadmap-line" />{roadmap.plan.map((phase, index) => <div className="roadmap-step" key={`${phase.label}-${phase.title}`}><div className="roadmap-marker">{index + 1}</div><div className="roadmap-copy"><span>{phase.label}</span><h3>{phase.title}</h3><p>{phase.detail}</p></div></div>)}</div><div className="prepare-note"><Clock3 size={15} /><span>Built around {roadmap.requirements.slice(0, 3).join(', ')} and your existing {roadmap.currentSkills.slice(0, 2).join(' + ')} skills.</span></div></>}</div>{!state.loading && !state.error && <div className="prepare-footer"><button className="button dark-button" onClick={onClose}>I’m ready to start <ArrowRight size={15} /></button></div>}</div></div>
}
