import { createRoot } from 'react-dom/client'
import { useState } from 'react'
import {
  ArrowUpRight, Bell, Bookmark, CalendarDays, Check, ChevronRight, CircleHelp,
  Compass, FileText, Flame, GraduationCap, Heart, Inbox, LayoutDashboard,
  Lightbulb, MapPin, Menu, Plus, Search, Sparkles, Target, Trophy, Upload,
  Users, X, Zap
} from 'lucide-react'
import './styles.css'

const opportunities = [
  { id: 1, title: 'Build for Bharat AI Hackathon', org: 'Microsoft Reactor', type: 'Hackathon', category: 'stretch', date: 'Oct 18–20, 2026', deadline: 'Oct 10', location: 'Online · India', score: 88, color: 'coral', tags: ['Python', 'AI/ML'], reason: 'You selected AI/ML as a growth goal and already know Python. This is a high-upside stretch into building real ML products.', skills: ['Python', 'React'], missing: ['Model APIs', 'Prompt design'] },
  { id: 2, title: 'CodeSprint Web Challenge', org: 'Devfolio', type: 'Hackathon', category: 'perfect', date: 'Sep 27–28, 2026', deadline: 'Sep 21', location: 'Bengaluru · Hybrid', score: 96, color: 'blue', tags: ['React', 'Web'], reason: 'A near-perfect match for your React and web development skills, with a team format you said you enjoy.', skills: ['React', 'JavaScript', 'Git'], missing: ['None'] },
  { id: 3, title: 'Women in Tech AI Summit', org: 'Google for Developers', type: 'Conference', category: 'dream', date: 'Nov 06, 2026', deadline: 'Oct 28', location: 'Mumbai · In person', score: 74, color: 'pink', tags: ['AI/ML', 'Community'], reason: 'You marked AI conferences as a dream opportunity. Your motivation matters here more than your current ML experience.', skills: ['Curiosity', 'Python'], missing: ['ML fundamentals'] },
  { id: 4, title: 'Secure the Stack CTF', org: 'Null Community', type: 'Competition', category: 'growth', date: 'Oct 03, 2026', deadline: 'Sep 29', location: 'Online', score: 68, color: 'green', tags: ['Cybersecurity', 'Teams'], reason: 'Cybersecurity is outside your current focus, but you want to grow your problem-solving skills. Start with the beginner track.', skills: ['Problem solving', 'Python'], missing: ['Linux', 'Web security'] },
  { id: 5, title: 'GenAI Product Workshop', org: 'Product School', type: 'Workshop', category: 'perfect', date: 'Sep 24, 2026', deadline: 'Sep 22', location: 'Online', score: 91, color: 'yellow', tags: ['GenAI', 'Product'], reason: 'It matches your interest in GenAI and your goal to turn technical skills into useful products.', skills: ['Python', 'Creativity'], missing: ['Product discovery'] },
  { id: 6, title: 'Pitch It! Student Venture Cup', org: 'IIM Bangalore', type: 'Competition', category: 'growth', date: 'Oct 11, 2026', deadline: 'Oct 04', location: 'Bengaluru · In person', score: 61, color: 'purple', tags: ['Entrepreneurship', 'Pitching'], reason: 'You want to improve communication and entrepreneurship. This gives you a safe first stage to practice both.', skills: ['Creativity'], missing: ['Storytelling', 'Market sizing'] },
]

const categoryMeta = {
  perfect: { label: 'Perfect fit', icon: Zap, className: 'perfect' },
  stretch: { label: 'Stretch opportunity', icon: Flame, className: 'stretch' },
  dream: { label: 'Dream opportunity', icon: Heart, className: 'dream' },
  growth: { label: 'Growth opportunity', icon: Sparkles, className: 'growth' },
}

function App() {
  const [activeNav, setActiveNav] = useState('Dashboard')
  const [selected, setSelected] = useState(null)
  const [modal, setModal] = useState(null)
  const [reminders, setReminders] = useState([])
  const [saved, setSaved] = useState([])
  const [dnaDone, setDnaDone] = useState(false)
  const [query, setQuery] = useState('')

  const toggleReminder = (id) => setReminders((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const toggleSaved = (id) => setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const filtered = opportunities.filter((item) => `${item.title} ${item.type} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><span /></span><span>grow<span>via</span></span></div>
      <div className="profile-chip"><div className="avatar">AS</div><div><strong>Ananya Shah</strong><span>Student profile</span></div><ChevronRight size={15} /></div>
      <nav className="main-nav">
        {[[LayoutDashboard, 'Dashboard'], [Compass, 'Explore'], [Bookmark, 'Saved'], [CalendarDays, 'My calendar']].map(([Icon, label]) => <button className={activeNav === label ? 'nav-item active' : 'nav-item'} onClick={() => setActiveNav(label)} key={label}><Icon size={18} />{label}{label === 'Saved' && saved.length > 0 ? <em>{saved.length}</em> : null}</button>)}
      </nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setModal('organizer')}><Upload size={18} />Organizer tools</button><button className="nav-item"><CircleHelp size={18} />Help center</button><div className="upgrade-card"><Sparkles size={17} /><strong>Make your profile sharper</strong><p>Complete your DNA to unlock smarter matches.</p><button onClick={() => setModal('dna')}>Complete DNA <ArrowUpRight size={14} /></button></div></div>
    </aside>

    <main className="main-content">
      <header className="topbar"><button className="mobile-menu"><Menu size={20} /></button><div className="breadcrumb"><span>{activeNav}</span><ChevronRight size={14} /><strong>2026</strong></div><div className="top-actions"><label className="search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search opportunities" /></label><button className="icon-button notification"><Bell size={19} /><i /></button><div className="avatar small">AS</div></div></header>
      {activeNav === 'Dashboard' ? <Dashboard filtered={filtered} dnaDone={dnaDone} setModal={setModal} selected={selected} setSelected={setSelected} reminders={reminders} toggleReminder={toggleReminder} saved={saved} toggleSaved={toggleSaved} setActiveNav={setActiveNav} /> : <BrowseView title={activeNav} opportunities={filtered} setSelected={setSelected} toggleSaved={toggleSaved} saved={saved} toggleReminder={toggleReminder} reminders={reminders} />}
    </main>

    {selected && <DetailModal opportunity={selected} close={() => setSelected(null)} reminder={reminders.includes(selected.id)} toggleReminder={() => toggleReminder(selected.id)} saved={saved.includes(selected.id)} toggleSaved={() => toggleSaved(selected.id)} setModal={setModal} />}
    {modal === 'dna' && <DnaModal close={() => setModal(null)} done={() => { setDnaDone(true); setModal(null) }} />}
    {modal === 'organizer' && <OrganizerModal close={() => setModal(null)} />}
    {modal === 'reflection' && <ReflectionModal close={() => setModal(null)} />}
  </div>
}

function Dashboard({ filtered, setModal, dnaDone, setSelected, reminders, toggleReminder, saved, toggleSaved, setActiveNav }) {
  const picks = filtered.slice(0, 4)
  return <div className="page-wrap">
    <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-dot" />Tuesday, September 15, 2026</div><h1>Good morning, Ananya <span>✦</span></h1><p className="lead">Here are a few opportunities that could move you forward.</p></div><button className="button secondary" onClick={() => setModal('dna')}><Target size={16} />{dnaDone ? 'Update my DNA' : 'Shape your Opportunity DNA'}</button></section>
    <section className="radar-banner"><div className="radar-copy"><div className="eyebrow light"><Sparkles size={14} /> YOUR OPPORTUNITY RADAR</div><h2>3 opportunities worth<br /><em>your attention</em> this week.</h2><p>Matched to where you are and where you want to go next.</p><button className="button light-button" onClick={() => setActiveNav('Explore')}>Explore all matches <ArrowUpRight size={16} /></button></div><div className="radar-visual"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-ring ring-three" /><div className="radar-center"><span>88</span><small>match</small></div><i className="radar-point point-one" /><i className="radar-point point-two" /><i className="radar-point point-three" /></div><div className="radar-stat"><strong>12</strong><span>new this week</span><strong>04</strong><span>closing soon</span></div></section>
    <div className="section-heading"><div><div className="eyebrow">CURATED FOR YOU</div><h2>Your next moves</h2></div><button className="text-button" onClick={() => setActiveNav('Explore')}>View all <ArrowUpRight size={15} /></button></div>
    <div className="recommendations">{picks.map((item) => <OpportunityCard key={item.id} item={item} setSelected={setSelected} reminder={reminders.includes(item.id)} toggleReminder={toggleReminder} saved={saved.includes(item.id)} toggleSaved={toggleSaved} />)}</div>
    <div className="lower-grid"><section><div className="section-heading compact"><div><div className="eyebrow">DON'T MISS OUT</div><h2>Upcoming deadlines</h2></div><button className="text-button">Calendar <ArrowUpRight size={15} /></button></div><div className="deadline-list">{filtered.slice(0, 3).map((item, index) => <div className="deadline" key={item.id}><div className={`date-block ${index === 0 ? 'urgent' : ''}`}><b>{item.deadline.split(' ')[1]}</b><span>{item.deadline.split(' ')[0]}</span></div><div><strong>{item.title}</strong><span>{item.org} · {item.location}</span></div><span className={index === 0 ? 'deadline-tag urgent-text' : 'deadline-tag'}>{index === 0 ? '6 days left' : `${index + 1} weeks`}</span></div>)}</div></section><section className="reflection-card"><div className="reflection-icon"><Lightbulb size={20} /></div><div className="eyebrow">YOUR GROWTH LOOP</div><h3>Small reflection,<br />smarter matches.</h3><p>Tell us about your last experience and GrowVia will tune your radar.</p><button className="button dark-button" onClick={() => setModal('reflection')}>Add a reflection <ArrowUpRight size={15} /></button></section></div>
  </div>
}

function OpportunityCard({ item, setSelected, reminder, toggleReminder, saved, toggleSaved }) {
  const meta = categoryMeta[item.category]; const Icon = meta.icon
  return <article className={`opportunity-card ${item.color}`}><div className="card-top"><span className={`category-pill ${meta.className}`}><Icon size={13} />{meta.label}</span><button className="save-button" onClick={() => toggleSaved(item.id)} aria-label="Save opportunity"><Bookmark size={17} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="org-name">{item.org}</div><h3>{item.title}</h3><div className="match-row"><div className="match-score"><b>{item.score}%</b><span>match</span></div><div className="match-bar"><i style={{ width: `${item.score}%` }} /></div></div><div className="meta-row"><span><CalendarDays size={14} />{item.date}</span><span><MapPin size={14} />{item.location}</span></div><p className="reason"><Sparkles size={14} />{item.reason}</p><div className="card-actions"><button className="text-button" onClick={() => setSelected(item)}>Why this match <ArrowUpRight size={14} /></button><button className={reminder ? 'remind-button on' : 'remind-button'} onClick={() => toggleReminder(item.id)}><Bell size={14} />{reminder ? 'Reminded' : 'Remind me'}</button></div></article>
}

function BrowseView({ title, opportunities: items, setSelected, toggleSaved, saved, toggleReminder, reminders }) { return <div className="page-wrap"><section className="welcome-row browse-heading"><div><div className="eyebrow">YOUR OPPORTUNITY LIBRARY</div><h1>{title}</h1><p className="lead">Every option has a reason for being here.</p></div><button className="button dark-button"><Plus size={16} />Save a goal</button></section><div className="filter-row"><button className="filter active">All opportunities</button><button className="filter">Closing soon <span>4</span></button><button className="filter">Online</button><button className="filter">In person</button></div><div className="browse-grid">{items.map((item) => <OpportunityCard key={item.id} item={item} setSelected={setSelected} reminder={reminders.includes(item.id)} toggleReminder={toggleReminder} saved={saved.includes(item.id)} toggleSaved={toggleSaved} />)}</div></div> }

function DetailModal({ opportunity, close, reminder, toggleReminder, saved, toggleSaved, setModal }) { const meta = categoryMeta[opportunity.category]; const Icon = meta.icon; return <div className="modal-backdrop" onMouseDown={close}><div className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={close}><X size={18} /></button><div className={`detail-hero ${opportunity.color}`}><span className={`category-pill ${meta.className}`}><Icon size={14} />{meta.label}</span><div className="org-name">{opportunity.org}</div><h2>{opportunity.title}</h2><div className="detail-facts"><span><CalendarDays size={15} />{opportunity.date}</span><span><MapPin size={15} />{opportunity.location}</span><span><Users size={15} />Teams of 2–4</span></div></div><div className="detail-body"><div className="why-box"><Sparkles size={18} /><div><strong>Why am I seeing this?</strong><p>{opportunity.reason}</p></div></div><div className="detail-columns"><div><h4>You bring</h4><div className="skill-list">{opportunity.skills.map((skill) => <span className="skill good" key={skill}><Check size={13} />{skill}</span>)}</div></div><div><h4>Good next stretch</h4><div className="skill-list">{opportunity.missing.map((skill) => <span className="skill" key={skill}><Target size={13} />{skill}</span>)}</div></div></div><div className="detail-actions"><button className="button dark-button" onClick={() => opportunity.category === 'stretch' ? setModal('prepare') : toggleReminder()}>{opportunity.category === 'stretch' ? 'Prepare me' : reminder ? 'Reminder set' : 'Remind me'} <ArrowUpRight size={15} /></button><button className={saved ? 'button secondary saved' : 'button secondary'} onClick={toggleSaved}><Bookmark size={15} fill={saved ? 'currentColor' : 'none'} />{saved ? 'Saved' : 'Save opportunity'}</button></div></div></div></div> }

function DnaModal({ close, done }) { const [step, setStep] = useState(0); const [selected, setSelected] = useState([]); const steps = [{ title: 'What can you do today?', sub: 'Pick everything that feels familiar.', options: ['Python', 'JavaScript', 'React', 'C / C++', 'UI / UX', 'Public speaking', 'Data analysis', 'Git & GitHub'] }, { title: 'What pulls you in?', sub: 'We’ll use this to find your kind of room.', options: ['AI / ML', 'Web development', 'Entrepreneurship', 'Cybersecurity', 'Research', 'Design', 'Electronics', 'Community'] }, { title: 'Who are you becoming?', sub: 'Choose the growth goals that matter this semester.', options: ['Technical skills', 'Communication', 'Leadership', 'Teamwork', 'Problem solving', 'Creativity', 'Entrepreneurship', 'Confidence'] }]; const current = steps[step]; const pick = (option) => setSelected((items) => items.includes(option) ? items.filter((item) => item !== option) : [...items, option]); return <div className="modal-backdrop"><div className="dna-modal"><button className="close-button" onClick={close}><X size={18} /></button><div className="dna-progress"><span>YOUR OPPORTUNITY DNA</span><b>{step + 1} <i>/ 3</i></b><div><i style={{ width: `${((step + 1) / 3) * 100}%` }} /></div></div><div className="dna-content"><div className="dna-orb"><Target size={30} /></div><h2>{current.title}</h2><p>{current.sub}</p><div className="choice-grid">{current.options.map((option) => <button className={selected.includes(option) ? 'choice selected' : 'choice'} onClick={() => pick(option)} key={option}>{selected.includes(option) && <Check size={15} />}{option}</button>)}</div><div className="modal-footer"><button className="text-button" onClick={close}>Maybe later</button><button className="button dark-button" onClick={() => step < 2 ? setStep(step + 1) : done()}>{step < 2 ? 'Continue' : 'Build my radar'} <ChevronRight size={16} /></button></div></div></div></div> }

function OrganizerModal({ close }) { const [uploaded, setUploaded] = useState(false); return <div className="modal-backdrop"><div className="organizer-modal"><button className="close-button" onClick={close}><X size={18} /></button><div className="eyebrow">ORGANIZER STUDIO</div><h2>Turn your poster into an opportunity.</h2><p>Drop in an event poster and GrowVia will extract the details for you to review before publishing.</p>{!uploaded ? <button className="upload-zone" onClick={() => setUploaded(true)}><Upload size={25} /><strong>Upload event poster</strong><span>PNG, JPG or PDF · up to 10 MB</span></button> : <div className="extracted"><div className="poster-thumb"><FileText size={26} /><span>poster-ai-summit.png</span></div><div className="extract-status"><Check size={18} /><div><strong>Details extracted</strong><span>Ready for your review</span></div></div><label>Event name<input defaultValue="Women in Tech AI Summit" /></label><label>Registration deadline<input defaultValue="October 28, 2026" /></label><button className="button dark-button publish" onClick={close}>Review & publish <ArrowUpRight size={15} /></button></div>} </div></div> }

function ReflectionModal({ close }) { return <div className="modal-backdrop"><div className="reflection-modal"><button className="close-button" onClick={close}><X size={18} /></button><div className="reflection-icon"><Lightbulb size={20} /></div><div className="eyebrow">CLOSE THE LOOP</div><h2>How was your last event?</h2><p>Your honest take helps your next recommendation feel more like you.</p><div className="rating-row">{['Not for me', 'It was okay', 'Loved it'].map((item) => <button key={item}>♡<span>{item}</span></button>)}</div><label>What did you learn?<textarea placeholder="A new skill, a surprising idea, a person you met..." /></label><button className="button dark-button" onClick={close}>Save reflection <Check size={15} /></button></div></div> }

export default App

createRoot(document.getElementById('root')).render(<App />)